/**
 * Google Merchant Center XML feed serializer.
 *
 * Spec reference: https://support.google.com/merchants/answer/7052112
 *
 * The Merchant Center feed is the polled-XML pattern Google uses for:
 *   - Google Shopping ads
 *   - Free Shopping listings (launched 2020)
 *   - Product surfaces in Search + AI Overviews
 *
 * Required fields (per Google spec): id, title, description, link,
 * image_link, availability, price, brand, condition, gtin or mpn.
 *
 * One product per `<item>` element. RSS 2.0 envelope with the
 * `g:` (google) namespace for product-specific tags.
 *
 * v0 ships a single-product feed because the demo cartridge serves
 * one product per URL. A real multi-product feed would iterate over
 * many ProductSnapshots — same serializer, looped.
 */

import type { ProductSnapshot } from './types.js';

export interface MerchantCenterFeed {
  xml: string;
  itemCount: number;
}

export function toMerchantCenterXml(
  snapshot: ProductSnapshot,
  publicationLocale: string,
): MerchantCenterFeed {
  const item = renderItem(snapshot);
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">
  <channel>
    <title>${escapeXmlText(snapshot.vendor)} — product feed</title>
    <link>${escapeXmlText(snapshot.onlineStoreUrl ?? '')}</link>
    <description>Generated by @airo-js-examples/shopify-edge-worker. Snapshot ${snapshot.snapshotId} at ${escapeXmlText(publicationLocale)}.</description>
${item}
  </channel>
</rss>`;
  return { xml, itemCount: 1 };
}

function renderItem(p: ProductSnapshot): string {
  const availability = p.availableForSale ? 'in stock' : 'out of stock';
  const link = p.onlineStoreUrl ?? '';
  // Merchant Center wants a single image_link; additional images go in
  // additional_image_link (one per tag). Cap at the spec's 10-image limit.
  const additionalImages = p.images
    .filter((u) => u !== p.featuredImageUrl)
    .slice(0, 10)
    .map((url) => `      <g:additional_image_link>${escapeXmlText(url)}</g:additional_image_link>`)
    .join('\n');
  const compareAt = p.compareAtPrice
    ? `      <g:sale_price>${escapeXmlText(p.price.amount)} ${escapeXmlText(p.price.currencyCode)}</g:sale_price>\n` +
      `      <g:price>${escapeXmlText(p.compareAtPrice.amount)} ${escapeXmlText(p.compareAtPrice.currencyCode)}</g:price>`
    : `      <g:price>${escapeXmlText(p.price.amount)} ${escapeXmlText(p.price.currencyCode)}</g:price>`;

  return `    <item>
      <g:id>${escapeXmlText(p.id)}</g:id>
      <g:title>${escapeXmlText(p.title)}</g:title>
      <g:description>${escapeXmlText(p.description || p.title)}</g:description>
      <g:link>${escapeXmlText(link)}</g:link>
      <g:image_link>${escapeXmlText(p.featuredImageUrl ?? '')}</g:image_link>
${additionalImages ? additionalImages + '\n' : ''}      <g:availability>${escapeXmlText(availability)}</g:availability>
${compareAt}
      <g:brand>${escapeXmlText(p.vendor)}</g:brand>
      <g:condition>new</g:condition>
      <g:product_type>${escapeXmlText(p.productType)}</g:product_type>
${p.sku ? `      <g:mpn>${escapeXmlText(p.sku)}</g:mpn>\n` : ''}      <g:identifier_exists>${p.sku ? 'yes' : 'no'}</g:identifier_exists>
      <g:airo_snapshot_id>${escapeXmlText(p.snapshotId)}</g:airo_snapshot_id>
    </item>`;
}

function escapeXmlText(s: string): string {
  // XML text-content escapes — & < > " '. Same rules apply inside
  // attribute values, so this is conservative-safe for both.
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
